// <auto-generated />
namespace E_CommerceProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class aal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aal));
        
        string IMigrationMetadata.Id
        {
            get { return "202004021425022_aal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
